# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifrost" do
  name "bifrost"
  desc "Session context bridge between AI coding tools"
  homepage "https://github.com/kogungor/bifrost"
  version "0.6.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bifrost"

  on_macos do
    on_intel do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_darwin_amd64.tar.gz"
      sha256 "cb6d37ba645327d1397243aded740422e6e466a56b90badaad0a2dd34a12ceee"
    end
    on_arm do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_darwin_arm64.tar.gz"
      sha256 "5f435102eabd9fad65f3da330464c6ac56eed6d469d6195f64a944be6e970413"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_linux_amd64.tar.gz"
      sha256 "67f5b8843f998eb2084dbc1a56d2ae9bff34c259df00bc4f7fa1de10591afa84"
    end
    on_arm do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_linux_arm64.tar.gz"
      sha256 "e01fdea22fa901772247a8bd5f50fc39ceaf4b1818700c9eb19b91c9287947b0"
    end
  end

  # No zap stanza required
end
