# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifrost" do
  name "bifrost"
  desc "Session context bridge between AI coding tools"
  homepage "https://github.com/kogungor/bifrost"
  version "0.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bifrost"

  on_macos do
    on_intel do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_darwin_amd64.tar.gz"
      sha256 "4fb2574184190068432b2fa8dd40dc8f9450374988e9597d2bfbe4fb99fc3c18"
    end
    on_arm do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_darwin_arm64.tar.gz"
      sha256 "8225268bf1421a2c56c8d81b003a2332f26f7a5dc820937956d4e31df2cb08af"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_linux_amd64.tar.gz"
      sha256 "0e3facfb9deb2f3723fe7eb31159c0629fccf4a0d47596cd7c57e16e7854589c"
    end
    on_arm do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_linux_arm64.tar.gz"
      sha256 "270be5737912954505f22a666a7f2a7ef9458fc23adf1ce7a802d56e2cbadef7"
    end
  end

  # No zap stanza required
end
