# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifrost" do
  name "bifrost"
  desc "Session context bridge between AI coding tools"
  homepage "https://github.com/kogungor/bifrost"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bifrost"

  on_macos do
    on_intel do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_darwin_amd64.tar.gz"
      sha256 "d73116837c914baae402351ee046bbb410d0f55f3fbb8bd528562c269a1d62ff"
    end
    on_arm do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_darwin_arm64.tar.gz"
      sha256 "4cdaa476c78e4007dedaa99b432eaac6acc666c8d8555309b7bd4a16f4c22b44"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_linux_amd64.tar.gz"
      sha256 "87c23d78b00305fee61004236c30a06a5a6ebbd6e336c61296d0a05ed80720c9"
    end
    on_arm do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_linux_arm64.tar.gz"
      sha256 "95443a4546c06eb06cb3e23ebfa1e150dd5820be20881c28cb9719f3343cbc73"
    end
  end

  # No zap stanza required
end
